# -*- coding: utf-8 -*-

from scrapy.cmdline import execute

if __name__ == '__main__':
  # execute("scrapy crawl author".split())
  # execute("scrapy crawl courses".split())
  # execute("scrapy crawl douban".split())
  # execute("scrapy crawl fang".split())
  # execute("scrapy crawl hr".split())
  # execute("scrapy crawl imdb".split())
  execute("scrapy crawl jd".split())
  # execute("scrapy crawl kdl".split())
  # execute("scrapy crawl music".split())
  # execute("scrapy crawl myspider1".split())
  # execute("scrapy crawl myspider2".split())
  # execute("scrapy crawl q1".split())
  # execute("scrapy crawl q2".split())
  # execute("scrapy crawl q3".split())
  # execute("scrapy crawl q4".split())
  # execute("scrapy crawl qd".split())
  # execute("scrapy crawl qsbk".split())
  # execute("scrapy crawl renren".split())
  # execute("scrapy crawl sf".split())
  # execute("scrapy crawl taobao".split())
  # execute("scrapy crawl video".split())
  # execute("scrapy crawl wenku".split())
  # execute("scrapy crawl wx".split())
  # execute("scrapy crawl youdao".split())
  # execute("scrapy crawl mbook".split())
  # execute("scrapy crawl sbook".split())