from .AuthorPipeline import AuthorPipeline
from .DoubanPipeline import DoubanPipeline
from .JDPipeline import JDPipeline
from .QdPipeline import QdPipeline
from .TaobaoPipeline import TaobaoPipeline
from .FangPipeline import FangPipeline
from .CoursePipeline import EducsdnPipeline,CoursePipeline
from .HrPipeline import HrPipeline
from .WxPipeline import WxPipeline
from .KuaidailiPipeline import KuaidailiRedisPipeline,KuaidailiPipeline
from .DbookPipeline import DbookMasterPipeline,DbookSlavePipeline